// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: llmcenter.proto

package llmcenter

import (
	"context"

	"document_agent/app/llmcenter/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChatCompletionsRequest        = pb.ChatCompletionsRequest
	ChatCompletionsResponse       = pb.ChatCompletionsResponse
	ChatResumeRequest             = pb.ChatResumeRequest
	ChatResumeResponse            = pb.ChatResumeResponse
	Conversation                  = pb.Conversation
	ConvertMarkdownRequest        = pb.ConvertMarkdownRequest
	ConvertMarkdownResponse       = pb.ConvertMarkdownResponse
	Document                      = pb.Document
	EditDocumentRequest           = pb.EditDocumentRequest
	EditDocumentResponse          = pb.EditDocumentResponse
	FileInfo                      = pb.FileInfo
	FileReference                 = pb.FileReference
	FileUploadRequest             = pb.FileUploadRequest
	FileUploadResponse            = pb.FileUploadResponse
	GetConversationDetailRequest  = pb.GetConversationDetailRequest
	GetConversationDetailResponse = pb.GetConversationDetailResponse
	GetConversationsRequest       = pb.GetConversationsRequest
	GetConversationsResponse      = pb.GetConversationsResponse
	GetDocumentDetailRequest      = pb.GetDocumentDetailRequest
	GetDocumentDetailResponse     = pb.GetDocumentDetailResponse
	GetHistoryDataRequest         = pb.GetHistoryDataRequest
	GetHistoryDataResponse        = pb.GetHistoryDataResponse
	HistoryData                   = pb.HistoryData
	Message                       = pb.Message
	Reference                     = pb.Reference
	SSEEndEvent                   = pb.SSEEndEvent
	SSEInterruptEvent             = pb.SSEInterruptEvent
	SSEMessageEvent               = pb.SSEMessageEvent
	UpdateDocumentRequest         = pb.UpdateDocumentRequest
	UpdateDocumentResponse        = pb.UpdateDocumentResponse

	LlmCenter interface {
		// RPC 方法: ChatCompletions
		ChatCompletions(ctx context.Context, in *ChatCompletionsRequest, opts ...grpc.CallOption) (pb.LlmCenter_ChatCompletionsClient, error)
		// RPC 方法: ChatResume
		ChatResume(ctx context.Context, in *ChatResumeRequest, opts ...grpc.CallOption) (pb.LlmCenter_ChatResumeClient, error)
		// RPC 方法: FileUpload
		FileUpload(ctx context.Context, opts ...grpc.CallOption) (pb.LlmCenter_FileUploadClient, error)
		// RPC 方法: GetConversations
		GetConversations(ctx context.Context, in *GetConversationsRequest, opts ...grpc.CallOption) (*GetConversationsResponse, error)
		// RPC 方法: GetConversationDetail
		GetConversationDetail(ctx context.Context, in *GetConversationDetailRequest, opts ...grpc.CallOption) (*GetConversationDetailResponse, error)
		// RPC 方法: GetDocumentDetail
		GetDocumentDetail(ctx context.Context, in *GetDocumentDetailRequest, opts ...grpc.CallOption) (*GetDocumentDetailResponse, error)
		// RPC 方法: GetHistoryData
		GetHistoryData(ctx context.Context, in *GetHistoryDataRequest, opts ...grpc.CallOption) (*GetHistoryDataResponse, error)
		// RPC 方法: EditDocumentRequest
		EditDocument(ctx context.Context, in *EditDocumentRequest, opts ...grpc.CallOption) (pb.LlmCenter_EditDocumentClient, error)
		// RPC 方法: UpdateDocumentRequest
		UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error)
		// RPC 方法: DownloadFileRequest
		ConvertMarkdown(ctx context.Context, in *ConvertMarkdownRequest, opts ...grpc.CallOption) (*ConvertMarkdownResponse, error)
	}

	defaultLlmCenter struct {
		cli zrpc.Client
	}
)

func NewLlmCenter(cli zrpc.Client) LlmCenter {
	return &defaultLlmCenter{
		cli: cli,
	}
}

// RPC 方法: ChatCompletions
func (m *defaultLlmCenter) ChatCompletions(ctx context.Context, in *ChatCompletionsRequest, opts ...grpc.CallOption) (pb.LlmCenter_ChatCompletionsClient, error) {
	client := pb.NewLlmCenterClient(m.cli.Conn())
	return client.ChatCompletions(ctx, in, opts...)
}

// RPC 方法: ChatResume
func (m *defaultLlmCenter) ChatResume(ctx context.Context, in *ChatResumeRequest, opts ...grpc.CallOption) (pb.LlmCenter_ChatResumeClient, error) {
	client := pb.NewLlmCenterClient(m.cli.Conn())
	return client.ChatResume(ctx, in, opts...)
}

// RPC 方法: FileUpload
func (m *defaultLlmCenter) FileUpload(ctx context.Context, opts ...grpc.CallOption) (pb.LlmCenter_FileUploadClient, error) {
	client := pb.NewLlmCenterClient(m.cli.Conn())
	return client.FileUpload(ctx, opts...)
}

// RPC 方法: GetConversations
func (m *defaultLlmCenter) GetConversations(ctx context.Context, in *GetConversationsRequest, opts ...grpc.CallOption) (*GetConversationsResponse, error) {
	client := pb.NewLlmCenterClient(m.cli.Conn())
	return client.GetConversations(ctx, in, opts...)
}

// RPC 方法: GetConversationDetail
func (m *defaultLlmCenter) GetConversationDetail(ctx context.Context, in *GetConversationDetailRequest, opts ...grpc.CallOption) (*GetConversationDetailResponse, error) {
	client := pb.NewLlmCenterClient(m.cli.Conn())
	return client.GetConversationDetail(ctx, in, opts...)
}

// RPC 方法: GetDocumentDetail
func (m *defaultLlmCenter) GetDocumentDetail(ctx context.Context, in *GetDocumentDetailRequest, opts ...grpc.CallOption) (*GetDocumentDetailResponse, error) {
	client := pb.NewLlmCenterClient(m.cli.Conn())
	return client.GetDocumentDetail(ctx, in, opts...)
}

// RPC 方法: GetHistoryData
func (m *defaultLlmCenter) GetHistoryData(ctx context.Context, in *GetHistoryDataRequest, opts ...grpc.CallOption) (*GetHistoryDataResponse, error) {
	client := pb.NewLlmCenterClient(m.cli.Conn())
	return client.GetHistoryData(ctx, in, opts...)
}

// RPC 方法: EditDocumentRequest
func (m *defaultLlmCenter) EditDocument(ctx context.Context, in *EditDocumentRequest, opts ...grpc.CallOption) (pb.LlmCenter_EditDocumentClient, error) {
	client := pb.NewLlmCenterClient(m.cli.Conn())
	return client.EditDocument(ctx, in, opts...)
}

// RPC 方法: UpdateDocumentRequest
func (m *defaultLlmCenter) UpdateDocument(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error) {
	client := pb.NewLlmCenterClient(m.cli.Conn())
	return client.UpdateDocument(ctx, in, opts...)
}

// RPC 方法: DownloadFileRequest
func (m *defaultLlmCenter) ConvertMarkdown(ctx context.Context, in *ConvertMarkdownRequest, opts ...grpc.CallOption) (*ConvertMarkdownResponse, error) {
	client := pb.NewLlmCenterClient(m.cli.Conn())
	return client.ConvertMarkdown(ctx, in, opts...)
}
