// 指定使用 proto3 语法。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: llmcenter.proto

// 定义包名，这有助于防止不同 .proto 文件之间的命名冲突。

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求: 发起新对话或继续对话
type ChatCompletionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                 //api层传来的用户id
	ConversationId   string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`          // 可选: 现有会话ID。如果为空，将创建新会话。
	Documenttype     string                 `protobuf:"bytes,2,opt,name=documenttype,proto3" json:"documenttype,omitempty"`                                    // 文章类型
	Information      string                 `protobuf:"bytes,7,opt,name=information,proto3" json:"information,omitempty"`                                      // 基本信息
	Requests         string                 `protobuf:"bytes,8,opt,name=requests,proto3" json:"requests,omitempty"`                                            // 特殊要求
	UseKnowledgeBase bool                   `protobuf:"varint,3,opt,name=use_knowledge_base,json=useKnowledgeBase,proto3" json:"use_knowledge_base,omitempty"` // 可选: 是否使用自定义知识库。
	KnowledgeBaseId  string                 `protobuf:"bytes,4,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`     // 可选: 如果 use_knowledge_base 为 true，则需要提供知识库ID。
	References       []*Reference           `protobuf:"bytes,5,rep,name=references,proto3" json:"references,omitempty"`                                        // 可选: 引用列表，例如引用的文件。
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatCompletionsRequest) Reset() {
	*x = ChatCompletionsRequest{}
	mi := &file_llmcenter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionsRequest) ProtoMessage() {}

func (x *ChatCompletionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionsRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionsRequest) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{0}
}

func (x *ChatCompletionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatCompletionsRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatCompletionsRequest) GetDocumenttype() string {
	if x != nil {
		return x.Documenttype
	}
	return ""
}

func (x *ChatCompletionsRequest) GetInformation() string {
	if x != nil {
		return x.Information
	}
	return ""
}

func (x *ChatCompletionsRequest) GetRequests() string {
	if x != nil {
		return x.Requests
	}
	return ""
}

func (x *ChatCompletionsRequest) GetUseKnowledgeBase() bool {
	if x != nil {
		return x.UseKnowledgeBase
	}
	return false
}

func (x *ChatCompletionsRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

func (x *ChatCompletionsRequest) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

// 响应流: ChatCompletions 的流式响应体
// 使用 oneof 来模拟 SSE 中的不同 event 类型。
type ChatCompletionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ChatCompletionsResponse_Message
	//	*ChatCompletionsResponse_Interrupt
	//	*ChatCompletionsResponse_End
	Event         isChatCompletionsResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionsResponse) Reset() {
	*x = ChatCompletionsResponse{}
	mi := &file_llmcenter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionsResponse) ProtoMessage() {}

func (x *ChatCompletionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionsResponse.ProtoReflect.Descriptor instead.
func (*ChatCompletionsResponse) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{1}
}

func (x *ChatCompletionsResponse) GetEvent() isChatCompletionsResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ChatCompletionsResponse) GetMessage() *SSEMessageEvent {
	if x != nil {
		if x, ok := x.Event.(*ChatCompletionsResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ChatCompletionsResponse) GetInterrupt() *SSEInterruptEvent {
	if x != nil {
		if x, ok := x.Event.(*ChatCompletionsResponse_Interrupt); ok {
			return x.Interrupt
		}
	}
	return nil
}

func (x *ChatCompletionsResponse) GetEnd() *SSEEndEvent {
	if x != nil {
		if x, ok := x.Event.(*ChatCompletionsResponse_End); ok {
			return x.End
		}
	}
	return nil
}

type isChatCompletionsResponse_Event interface {
	isChatCompletionsResponse_Event()
}

type ChatCompletionsResponse_Message struct {
	Message *SSEMessageEvent `protobuf:"bytes,1,opt,name=message,proto3,oneof"` // 对应 event: message
}

type ChatCompletionsResponse_Interrupt struct {
	Interrupt *SSEInterruptEvent `protobuf:"bytes,2,opt,name=interrupt,proto3,oneof"` // 对应 event: interrupt
}

type ChatCompletionsResponse_End struct {
	End *SSEEndEvent `protobuf:"bytes,3,opt,name=end,proto3,oneof"` // 对应 event: end
}

func (*ChatCompletionsResponse_Message) isChatCompletionsResponse_Event() {}

func (*ChatCompletionsResponse_Interrupt) isChatCompletionsResponse_Event() {}

func (*ChatCompletionsResponse_End) isChatCompletionsResponse_Event() {}

// 请求: 在中断后继续流程
type ChatResumeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        //api层传来的用户id
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 必选: 当前会话的ID。
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                     // 必选: 用户在前端编辑器中确认后的完整内容。
	TemplateId     string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`             // 可选: 如果用户在这一步选择了模板。
	Documenttype   string                 `protobuf:"bytes,5,opt,name=documenttype,proto3" json:"documenttype,omitempty"`                           // 新增：续写的文档类型
	References     []*Reference           `protobuf:"bytes,6,rep,name=references,proto3" json:"references,omitempty"`                               // 新增：附件引用（图片/文档）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatResumeRequest) Reset() {
	*x = ChatResumeRequest{}
	mi := &file_llmcenter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResumeRequest) ProtoMessage() {}

func (x *ChatResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResumeRequest.ProtoReflect.Descriptor instead.
func (*ChatResumeRequest) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResumeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatResumeRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatResumeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResumeRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *ChatResumeRequest) GetDocumenttype() string {
	if x != nil {
		return x.Documenttype
	}
	return ""
}

func (x *ChatResumeRequest) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

// 响应流: ChatResume 的流式响应体
type ChatResumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ChatResumeResponse_Message
	//	*ChatResumeResponse_End
	Event         isChatResumeResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResumeResponse) Reset() {
	*x = ChatResumeResponse{}
	mi := &file_llmcenter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResumeResponse) ProtoMessage() {}

func (x *ChatResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResumeResponse.ProtoReflect.Descriptor instead.
func (*ChatResumeResponse) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{3}
}

func (x *ChatResumeResponse) GetEvent() isChatResumeResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ChatResumeResponse) GetMessage() *SSEMessageEvent {
	if x != nil {
		if x, ok := x.Event.(*ChatResumeResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ChatResumeResponse) GetEnd() *SSEEndEvent {
	if x != nil {
		if x, ok := x.Event.(*ChatResumeResponse_End); ok {
			return x.End
		}
	}
	return nil
}

type isChatResumeResponse_Event interface {
	isChatResumeResponse_Event()
}

type ChatResumeResponse_Message struct {
	Message *SSEMessageEvent `protobuf:"bytes,1,opt,name=message,proto3,oneof"` // 对应 event: message
}

type ChatResumeResponse_End struct {
	End *SSEEndEvent `protobuf:"bytes,2,opt,name=end,proto3,oneof"` // 对应 event: end
}

func (*ChatResumeResponse_Message) isChatResumeResponse_Event() {}

func (*ChatResumeResponse_End) isChatResumeResponse_Event() {}

// 请求: 获取用户所有会话列表
// 通常 user_id 从 gRPC 的 metadata (类似 HTTP Header) 中获取，所以请求体为空。
type GetConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 可以选择在这里传递 user_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationsRequest) Reset() {
	*x = GetConversationsRequest{}
	mi := &file_llmcenter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsRequest) ProtoMessage() {}

func (x *GetConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsRequest.ProtoReflect.Descriptor instead.
func (*GetConversationsRequest) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{4}
}

func (x *GetConversationsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 响应: 会话列表
type GetConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Conversation        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationsResponse) Reset() {
	*x = GetConversationsResponse{}
	mi := &file_llmcenter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsResponse) ProtoMessage() {}

func (x *GetConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsResponse.ProtoReflect.Descriptor instead.
func (*GetConversationsResponse) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{5}
}

func (x *GetConversationsResponse) GetData() []*Conversation {
	if x != nil {
		return x.Data
	}
	return nil
}

// 请求: 获取单个会话的详细信息
type GetConversationDetailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 从路径中获取的会话ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationDetailRequest) Reset() {
	*x = GetConversationDetailRequest{}
	mi := &file_llmcenter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationDetailRequest) ProtoMessage() {}

func (x *GetConversationDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationDetailRequest.ProtoReflect.Descriptor instead.
func (*GetConversationDetailRequest) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{6}
}

func (x *GetConversationDetailRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// 响应: 单个会话的详细信息
type GetConversationDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	History        []*Message             `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationDetailResponse) Reset() {
	*x = GetConversationDetailResponse{}
	mi := &file_llmcenter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationDetailResponse) ProtoMessage() {}

func (x *GetConversationDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationDetailResponse.ProtoReflect.Descriptor instead.
func (*GetConversationDetailResponse) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{7}
}

func (x *GetConversationDetailResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetConversationDetailResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetConversationDetailResponse) GetHistory() []*Message {
	if x != nil {
		return x.History
	}
	return nil
}

// 请求：获取单个最终文档的详细信息
type GetDocumentDetailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDocumentDetailRequest) Reset() {
	*x = GetDocumentDetailRequest{}
	mi := &file_llmcenter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentDetailRequest) ProtoMessage() {}

func (x *GetDocumentDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentDetailRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentDetailRequest) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{8}
}

func (x *GetDocumentDetailRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// 单个文档
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_llmcenter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{9}
}

func (x *Document) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Document) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 响应：单个最终文档的详细信息
type GetDocumentDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Documents      []*Document            `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDocumentDetailResponse) Reset() {
	*x = GetDocumentDetailResponse{}
	mi := &file_llmcenter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentDetailResponse) ProtoMessage() {}

func (x *GetDocumentDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentDetailResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentDetailResponse) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{10}
}

func (x *GetDocumentDetailResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetDocumentDetailResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

// 请求: 获取单个会话的历史数据
type GetHistoryDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetHistoryDataRequest) Reset() {
	*x = GetHistoryDataRequest{}
	mi := &file_llmcenter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryDataRequest) ProtoMessage() {}

func (x *GetHistoryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryDataRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryDataRequest) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{11}
}

func (x *GetHistoryDataRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// 响应: 历史数据列表
type GetHistoryDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Items          []*HistoryData         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetHistoryDataResponse) Reset() {
	*x = GetHistoryDataResponse{}
	mi := &file_llmcenter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryDataResponse) ProtoMessage() {}

func (x *GetHistoryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryDataResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryDataResponse) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{12}
}

func (x *GetHistoryDataResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetHistoryDataResponse) GetItems() []*HistoryData {
	if x != nil {
		return x.Items
	}
	return nil
}

// 单个历史数据项
type HistoryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Documenttype  string                 `protobuf:"bytes,2,opt,name=documenttype,proto3" json:"documenttype,omitempty"`
	Information   string                 `protobuf:"bytes,3,opt,name=information,proto3" json:"information,omitempty"`
	Requests      string                 `protobuf:"bytes,4,opt,name=requests,proto3" json:"requests,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	References    []*FileReference       `protobuf:"bytes,6,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryData) Reset() {
	*x = HistoryData{}
	mi := &file_llmcenter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryData) ProtoMessage() {}

func (x *HistoryData) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryData.ProtoReflect.Descriptor instead.
func (*HistoryData) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{13}
}

func (x *HistoryData) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *HistoryData) GetDocumenttype() string {
	if x != nil {
		return x.Documenttype
	}
	return ""
}

func (x *HistoryData) GetInformation() string {
	if x != nil {
		return x.Information
	}
	return ""
}

func (x *HistoryData) GetRequests() string {
	if x != nil {
		return x.Requests
	}
	return ""
}

func (x *HistoryData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *HistoryData) GetReferences() []*FileReference {
	if x != nil {
		return x.References
	}
	return nil
}

// 文件
type FileReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Function      string                 `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReference) Reset() {
	*x = FileReference{}
	mi := &file_llmcenter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReference) ProtoMessage() {}

func (x *FileReference) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReference.ProtoReflect.Descriptor instead.
func (*FileReference) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{14}
}

func (x *FileReference) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileReference) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileReference) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

type EditDocumentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId   string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId        string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Prompt           string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	UseKnowledgeBase bool                   `protobuf:"varint,5,opt,name=use_knowledge_base,json=useKnowledgeBase,proto3" json:"use_knowledge_base,omitempty"`
	KnowledgeBaseId  string                 `protobuf:"bytes,6,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EditDocumentRequest) Reset() {
	*x = EditDocumentRequest{}
	mi := &file_llmcenter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditDocumentRequest) ProtoMessage() {}

func (x *EditDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditDocumentRequest.ProtoReflect.Descriptor instead.
func (*EditDocumentRequest) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{15}
}

func (x *EditDocumentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EditDocumentRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *EditDocumentRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EditDocumentRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *EditDocumentRequest) GetUseKnowledgeBase() bool {
	if x != nil {
		return x.UseKnowledgeBase
	}
	return false
}

func (x *EditDocumentRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

type EditDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*EditDocumentResponse_Message
	//	*EditDocumentResponse_End
	Event         isEditDocumentResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditDocumentResponse) Reset() {
	*x = EditDocumentResponse{}
	mi := &file_llmcenter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditDocumentResponse) ProtoMessage() {}

func (x *EditDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditDocumentResponse.ProtoReflect.Descriptor instead.
func (*EditDocumentResponse) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{16}
}

func (x *EditDocumentResponse) GetEvent() isEditDocumentResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EditDocumentResponse) GetMessage() *SSEMessageEvent {
	if x != nil {
		if x, ok := x.Event.(*EditDocumentResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *EditDocumentResponse) GetEnd() *SSEEndEvent {
	if x != nil {
		if x, ok := x.Event.(*EditDocumentResponse_End); ok {
			return x.End
		}
	}
	return nil
}

type isEditDocumentResponse_Event interface {
	isEditDocumentResponse_Event()
}

type EditDocumentResponse_Message struct {
	Message *SSEMessageEvent `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type EditDocumentResponse_End struct {
	End *SSEEndEvent `protobuf:"bytes,2,opt,name=end,proto3,oneof"`
}

func (*EditDocumentResponse_Message) isEditDocumentResponse_Event() {}

func (*EditDocumentResponse_End) isEditDocumentResponse_Event() {}

type UpdateDocumentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Prompt         string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_llmcenter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDocumentRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UpdateDocumentRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *UpdateDocumentRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type UpdateDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentResponse) Reset() {
	*x = UpdateDocumentResponse{}
	mi := &file_llmcenter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentResponse) ProtoMessage() {}

func (x *UpdateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentResponse.ProtoReflect.Descriptor instead.
func (*UpdateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ConvertMarkdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markdown      string                 `protobuf:"bytes,1,opt,name=markdown,proto3" json:"markdown,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`               // "pdf" | "docx"
	Information   []*InfoItem            `protobuf:"bytes,3,rep,name=information,proto3" json:"information,omitempty"` // 新：标题/文号等扩展字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertMarkdownRequest) Reset() {
	*x = ConvertMarkdownRequest{}
	mi := &file_llmcenter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertMarkdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertMarkdownRequest) ProtoMessage() {}

func (x *ConvertMarkdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertMarkdownRequest.ProtoReflect.Descriptor instead.
func (*ConvertMarkdownRequest) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{19}
}

func (x *ConvertMarkdownRequest) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *ConvertMarkdownRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConvertMarkdownRequest) GetInformation() []*InfoItem {
	if x != nil {
		return x.Information
	}
	return nil
}

type ConvertMarkdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertMarkdownResponse) Reset() {
	*x = ConvertMarkdownResponse{}
	mi := &file_llmcenter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertMarkdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertMarkdownResponse) ProtoMessage() {}

func (x *ConvertMarkdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertMarkdownResponse.ProtoReflect.Descriptor instead.
func (*ConvertMarkdownResponse) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{20}
}

func (x *ConvertMarkdownResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ConvertMarkdownResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ConvertMarkdownResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type InfoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // "title" | "docNo"（大小写不敏感）
	Contant       string                 `protobuf:"bytes,2,opt,name=contant,proto3" json:"contant,omitempty"` // 文本内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoItem) Reset() {
	*x = InfoItem{}
	mi := &file_llmcenter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoItem) ProtoMessage() {}

func (x *InfoItem) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoItem.ProtoReflect.Descriptor instead.
func (*InfoItem) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{21}
}

func (x *InfoItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InfoItem) GetContant() string {
	if x != nil {
		return x.Contant
	}
	return ""
}

// 请求流: 文件上传
// 客户端流的第一个消息必须是 FileInfo，后续消息为文件数据块。
type FileUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*FileUploadRequest_Info
	//	*FileUploadRequest_Chunk
	Data          isFileUploadRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_llmcenter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{22}
}

func (x *FileUploadRequest) GetData() isFileUploadRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileUploadRequest) GetInfo() *FileInfo {
	if x != nil {
		if x, ok := x.Data.(*FileUploadRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *FileUploadRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*FileUploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isFileUploadRequest_Data interface {
	isFileUploadRequest_Data()
}

type FileUploadRequest_Info struct {
	Info *FileInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"` // 文件元信息
}

type FileUploadRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // 文件数据块
}

func (*FileUploadRequest_Info) isFileUploadRequest_Data() {}

func (*FileUploadRequest_Chunk) isFileUploadRequest_Data() {}

// 消息: 文件元信息
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // 原始文件名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_llmcenter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{23}
}

func (x *FileInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// 响应: 文件上传成功
type FileUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`       // 后端生成的唯一文件ID
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // 原始文件名
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`                           // 文件的可访问URL
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                   // 成功消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadResponse) Reset() {
	*x = FileUploadResponse{}
	mi := &file_llmcenter_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadResponse) ProtoMessage() {}

func (x *FileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadResponse.ProtoReflect.Descriptor instead.
func (*FileUploadResponse) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{24}
}

func (x *FileUploadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileUploadResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileUploadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 结构: 对话中引用的对象
type Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                   // 引用类型, 例如: "file"
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // 文件ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_llmcenter_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{25}
}

func (x *Reference) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Reference) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

// 结构: 会话列表中的单个会话
type Conversation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 会话ID
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                         // 会话标题
	UpdatedAt      string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                // 更新时间 (RFC3339 格式的字符串)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_llmcenter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{26}
}

func (x *Conversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Conversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Conversation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 结构: 单条历史消息
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 消息ID
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                                  // 角色: "user" 或 "assistant"
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                            // 消息内容
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 内容类型, 例如: "text", "document_outline"
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`       // 创建时间 (RFC3339 格式的字符串)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_llmcenter_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{27}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 事件: message
// 用于闲聊或最终文档生成的流式文本
type SSEMessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"` // 流式返回的文本片段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSEMessageEvent) Reset() {
	*x = SSEMessageEvent{}
	mi := &file_llmcenter_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSEMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSEMessageEvent) ProtoMessage() {}

func (x *SSEMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSEMessageEvent.ProtoReflect.Descriptor instead.
func (*SSEMessageEvent) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{28}
}

func (x *SSEMessageEvent) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

// 事件: interrupt
// 用于触发文档生成，返回内容清单
type SSEInterruptEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ContentType    string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 内容类型, 例如 "document_outline"
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                            // 需要填入编辑器的内容清单
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SSEInterruptEvent) Reset() {
	*x = SSEInterruptEvent{}
	mi := &file_llmcenter_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSEInterruptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSEInterruptEvent) ProtoMessage() {}

func (x *SSEInterruptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSEInterruptEvent.ProtoReflect.Descriptor instead.
func (*SSEInterruptEvent) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{29}
}

func (x *SSEInterruptEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SSEInterruptEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SSEInterruptEvent) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *SSEInterruptEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 事件: end
// 表示一次完整的对话或流结束
type SSEEndEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 本次交互所属的会话ID
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                // 本次交互最终生成的完整消息ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SSEEndEvent) Reset() {
	*x = SSEEndEvent{}
	mi := &file_llmcenter_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSEEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSEEndEvent) ProtoMessage() {}

func (x *SSEEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSEEndEvent.ProtoReflect.Descriptor instead.
func (*SSEEndEvent) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{30}
}

func (x *SSEEndEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SSEEndEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ConvertMarkdownLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`         // "pdf" | "docx"
	Markdown      string                 `protobuf:"bytes,2,opt,name=markdown,proto3" json:"markdown,omitempty"` // 原文
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertMarkdownLinkRequest) Reset() {
	*x = ConvertMarkdownLinkRequest{}
	mi := &file_llmcenter_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertMarkdownLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertMarkdownLinkRequest) ProtoMessage() {}

func (x *ConvertMarkdownLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertMarkdownLinkRequest.ProtoReflect.Descriptor instead.
func (*ConvertMarkdownLinkRequest) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{31}
}

func (x *ConvertMarkdownLinkRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConvertMarkdownLinkRequest) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type ConvertMarkdownLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                          // 例如 export.pdf
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // application/pdf / ...
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`                                  // 相对存储路径（如 exports/2025-08-12/xxxxxx.pdf）
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`                                    // 可下载的完整 URL（Download.BaseURL + "?path=" + path）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertMarkdownLinkResponse) Reset() {
	*x = ConvertMarkdownLinkResponse{}
	mi := &file_llmcenter_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertMarkdownLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertMarkdownLinkResponse) ProtoMessage() {}

func (x *ConvertMarkdownLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmcenter_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertMarkdownLinkResponse.ProtoReflect.Descriptor instead.
func (*ConvertMarkdownLinkResponse) Descriptor() ([]byte, []int) {
	return file_llmcenter_proto_rawDescGZIP(), []int{32}
}

func (x *ConvertMarkdownLinkResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ConvertMarkdownLinkResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ConvertMarkdownLinkResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConvertMarkdownLinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_llmcenter_proto protoreflect.FileDescriptor

const file_llmcenter_proto_rawDesc = "" +
	"\n" +
	"\x0fllmcenter.proto\x12\tllmcenter\"\xcc\x02\n" +
	"\x16ChatCompletionsRequest\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\"\n" +
	"\fdocumenttype\x18\x02 \x01(\tR\fdocumenttype\x12 \n" +
	"\vinformation\x18\a \x01(\tR\vinformation\x12\x1a\n" +
	"\brequests\x18\b \x01(\tR\brequests\x12,\n" +
	"\x12use_knowledge_base\x18\x03 \x01(\bR\x10useKnowledgeBase\x12*\n" +
	"\x11knowledge_base_id\x18\x04 \x01(\tR\x0fknowledgeBaseId\x124\n" +
	"\n" +
	"references\x18\x05 \x03(\v2\x14.llmcenter.ReferenceR\n" +
	"references\"\xc4\x01\n" +
	"\x17ChatCompletionsResponse\x126\n" +
	"\amessage\x18\x01 \x01(\v2\x1a.llmcenter.SSEMessageEventH\x00R\amessage\x12<\n" +
	"\tinterrupt\x18\x02 \x01(\v2\x1c.llmcenter.SSEInterruptEventH\x00R\tinterrupt\x12*\n" +
	"\x03end\x18\x03 \x01(\v2\x16.llmcenter.SSEEndEventH\x00R\x03endB\a\n" +
	"\x05event\"\xea\x01\n" +
	"\x11ChatResumeRequest\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12\"\n" +
	"\fdocumenttype\x18\x05 \x01(\tR\fdocumenttype\x124\n" +
	"\n" +
	"references\x18\x06 \x03(\v2\x14.llmcenter.ReferenceR\n" +
	"references\"\x81\x01\n" +
	"\x12ChatResumeResponse\x126\n" +
	"\amessage\x18\x01 \x01(\v2\x1a.llmcenter.SSEMessageEventH\x00R\amessage\x12*\n" +
	"\x03end\x18\x02 \x01(\v2\x16.llmcenter.SSEEndEventH\x00R\x03endB\a\n" +
	"\x05event\"2\n" +
	"\x17GetConversationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"G\n" +
	"\x18GetConversationsResponse\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.llmcenter.ConversationR\x04data\"G\n" +
	"\x1cGetConversationDetailRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"\x8c\x01\n" +
	"\x1dGetConversationDetailResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12,\n" +
	"\ahistory\x18\x03 \x03(\v2\x12.llmcenter.MessageR\ahistory\"C\n" +
	"\x18GetDocumentDetailRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"b\n" +
	"\bDocument\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"w\n" +
	"\x19GetDocumentDetailResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x121\n" +
	"\tdocuments\x18\x02 \x03(\v2\x13.llmcenter.DocumentR\tdocuments\"@\n" +
	"\x15GetHistoryDataRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"o\n" +
	"\x16GetHistoryDataResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.llmcenter.HistoryDataR\x05items\"\xe7\x01\n" +
	"\vHistoryData\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\"\n" +
	"\fdocumenttype\x18\x02 \x01(\tR\fdocumenttype\x12 \n" +
	"\vinformation\x18\x03 \x01(\tR\vinformation\x12\x1a\n" +
	"\brequests\x18\x04 \x01(\tR\brequests\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x128\n" +
	"\n" +
	"references\x18\x06 \x03(\v2\x18.llmcenter.FileReferenceR\n" +
	"references\"`\n" +
	"\rFileReference\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\bfunction\x18\x03 \x01(\tR\bfunction\"\xe8\x01\n" +
	"\x13EditDocumentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12,\n" +
	"\x12use_knowledge_base\x18\x05 \x01(\bR\x10useKnowledgeBase\x12*\n" +
	"\x11knowledge_base_id\x18\x06 \x01(\tR\x0fknowledgeBaseId\"\x83\x01\n" +
	"\x14EditDocumentResponse\x126\n" +
	"\amessage\x18\x01 \x01(\v2\x1a.llmcenter.SSEMessageEventH\x00R\amessage\x12*\n" +
	"\x03end\x18\x02 \x01(\v2\x16.llmcenter.SSEEndEventH\x00R\x03endB\a\n" +
	"\x05event\"w\n" +
	"\x15UpdateDocumentRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\"2\n" +
	"\x16UpdateDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x7f\n" +
	"\x16ConvertMarkdownRequest\x12\x1a\n" +
	"\bmarkdown\x18\x01 \x01(\tR\bmarkdown\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x125\n" +
	"\vinformation\x18\x03 \x03(\v2\x13.llmcenter.InfoItemR\vinformation\"l\n" +
	"\x17ConvertMarkdownResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"8\n" +
	"\bInfoItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontant\x18\x02 \x01(\tR\acontant\"^\n" +
	"\x11FileUploadRequest\x12)\n" +
	"\x04info\x18\x01 \x01(\v2\x13.llmcenter.FileInfoH\x00R\x04info\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"'\n" +
	"\bFileInfo\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\"v\n" +
	"\x12FileUploadResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"8\n" +
	"\tReference\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\"l\n" +
	"\fConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\"\x89\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"'\n" +
	"\x0fSSEMessageEvent\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\"\x98\x01\n" +
	"\x11SSEInterruptEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"U\n" +
	"\vSSEEndEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"L\n" +
	"\x1aConvertMarkdownLinkRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bmarkdown\x18\x02 \x01(\tR\bmarkdown\"\x82\x01\n" +
	"\x1bConvertMarkdownLinkResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url2\xeb\a\n" +
	"\tLlmCenter\x12Z\n" +
	"\x0fChatCompletions\x12!.llmcenter.ChatCompletionsRequest\x1a\".llmcenter.ChatCompletionsResponse0\x01\x12K\n" +
	"\n" +
	"ChatResume\x12\x1c.llmcenter.ChatResumeRequest\x1a\x1d.llmcenter.ChatResumeResponse0\x01\x12K\n" +
	"\n" +
	"FileUpload\x12\x1c.llmcenter.FileUploadRequest\x1a\x1d.llmcenter.FileUploadResponse(\x01\x12[\n" +
	"\x10GetConversations\x12\".llmcenter.GetConversationsRequest\x1a#.llmcenter.GetConversationsResponse\x12j\n" +
	"\x15GetConversationDetail\x12'.llmcenter.GetConversationDetailRequest\x1a(.llmcenter.GetConversationDetailResponse\x12^\n" +
	"\x11GetDocumentDetail\x12#.llmcenter.GetDocumentDetailRequest\x1a$.llmcenter.GetDocumentDetailResponse\x12U\n" +
	"\x0eGetHistoryData\x12 .llmcenter.GetHistoryDataRequest\x1a!.llmcenter.GetHistoryDataResponse\x12Q\n" +
	"\fEditDocument\x12\x1e.llmcenter.EditDocumentRequest\x1a\x1f.llmcenter.EditDocumentResponse0\x01\x12U\n" +
	"\x0eUpdateDocument\x12 .llmcenter.UpdateDocumentRequest\x1a!.llmcenter.UpdateDocumentResponse\x12X\n" +
	"\x0fConvertMarkdown\x12!.llmcenter.ConvertMarkdownRequest\x1a\".llmcenter.ConvertMarkdownResponse\x12d\n" +
	"\x13ConvertMarkdownLink\x12%.llmcenter.ConvertMarkdownLinkRequest\x1a&.llmcenter.ConvertMarkdownLinkResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_llmcenter_proto_rawDescOnce sync.Once
	file_llmcenter_proto_rawDescData []byte
)

func file_llmcenter_proto_rawDescGZIP() []byte {
	file_llmcenter_proto_rawDescOnce.Do(func() {
		file_llmcenter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmcenter_proto_rawDesc), len(file_llmcenter_proto_rawDesc)))
	})
	return file_llmcenter_proto_rawDescData
}

var file_llmcenter_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_llmcenter_proto_goTypes = []any{
	(*ChatCompletionsRequest)(nil),        // 0: llmcenter.ChatCompletionsRequest
	(*ChatCompletionsResponse)(nil),       // 1: llmcenter.ChatCompletionsResponse
	(*ChatResumeRequest)(nil),             // 2: llmcenter.ChatResumeRequest
	(*ChatResumeResponse)(nil),            // 3: llmcenter.ChatResumeResponse
	(*GetConversationsRequest)(nil),       // 4: llmcenter.GetConversationsRequest
	(*GetConversationsResponse)(nil),      // 5: llmcenter.GetConversationsResponse
	(*GetConversationDetailRequest)(nil),  // 6: llmcenter.GetConversationDetailRequest
	(*GetConversationDetailResponse)(nil), // 7: llmcenter.GetConversationDetailResponse
	(*GetDocumentDetailRequest)(nil),      // 8: llmcenter.GetDocumentDetailRequest
	(*Document)(nil),                      // 9: llmcenter.Document
	(*GetDocumentDetailResponse)(nil),     // 10: llmcenter.GetDocumentDetailResponse
	(*GetHistoryDataRequest)(nil),         // 11: llmcenter.GetHistoryDataRequest
	(*GetHistoryDataResponse)(nil),        // 12: llmcenter.GetHistoryDataResponse
	(*HistoryData)(nil),                   // 13: llmcenter.HistoryData
	(*FileReference)(nil),                 // 14: llmcenter.FileReference
	(*EditDocumentRequest)(nil),           // 15: llmcenter.EditDocumentRequest
	(*EditDocumentResponse)(nil),          // 16: llmcenter.EditDocumentResponse
	(*UpdateDocumentRequest)(nil),         // 17: llmcenter.UpdateDocumentRequest
	(*UpdateDocumentResponse)(nil),        // 18: llmcenter.UpdateDocumentResponse
	(*ConvertMarkdownRequest)(nil),        // 19: llmcenter.ConvertMarkdownRequest
	(*ConvertMarkdownResponse)(nil),       // 20: llmcenter.ConvertMarkdownResponse
	(*InfoItem)(nil),                      // 21: llmcenter.InfoItem
	(*FileUploadRequest)(nil),             // 22: llmcenter.FileUploadRequest
	(*FileInfo)(nil),                      // 23: llmcenter.FileInfo
	(*FileUploadResponse)(nil),            // 24: llmcenter.FileUploadResponse
	(*Reference)(nil),                     // 25: llmcenter.Reference
	(*Conversation)(nil),                  // 26: llmcenter.Conversation
	(*Message)(nil),                       // 27: llmcenter.Message
	(*SSEMessageEvent)(nil),               // 28: llmcenter.SSEMessageEvent
	(*SSEInterruptEvent)(nil),             // 29: llmcenter.SSEInterruptEvent
	(*SSEEndEvent)(nil),                   // 30: llmcenter.SSEEndEvent
	(*ConvertMarkdownLinkRequest)(nil),    // 31: llmcenter.ConvertMarkdownLinkRequest
	(*ConvertMarkdownLinkResponse)(nil),   // 32: llmcenter.ConvertMarkdownLinkResponse
}
var file_llmcenter_proto_depIdxs = []int32{
	25, // 0: llmcenter.ChatCompletionsRequest.references:type_name -> llmcenter.Reference
	28, // 1: llmcenter.ChatCompletionsResponse.message:type_name -> llmcenter.SSEMessageEvent
	29, // 2: llmcenter.ChatCompletionsResponse.interrupt:type_name -> llmcenter.SSEInterruptEvent
	30, // 3: llmcenter.ChatCompletionsResponse.end:type_name -> llmcenter.SSEEndEvent
	25, // 4: llmcenter.ChatResumeRequest.references:type_name -> llmcenter.Reference
	28, // 5: llmcenter.ChatResumeResponse.message:type_name -> llmcenter.SSEMessageEvent
	30, // 6: llmcenter.ChatResumeResponse.end:type_name -> llmcenter.SSEEndEvent
	26, // 7: llmcenter.GetConversationsResponse.data:type_name -> llmcenter.Conversation
	27, // 8: llmcenter.GetConversationDetailResponse.history:type_name -> llmcenter.Message
	9,  // 9: llmcenter.GetDocumentDetailResponse.documents:type_name -> llmcenter.Document
	13, // 10: llmcenter.GetHistoryDataResponse.items:type_name -> llmcenter.HistoryData
	14, // 11: llmcenter.HistoryData.references:type_name -> llmcenter.FileReference
	28, // 12: llmcenter.EditDocumentResponse.message:type_name -> llmcenter.SSEMessageEvent
	30, // 13: llmcenter.EditDocumentResponse.end:type_name -> llmcenter.SSEEndEvent
	21, // 14: llmcenter.ConvertMarkdownRequest.information:type_name -> llmcenter.InfoItem
	23, // 15: llmcenter.FileUploadRequest.info:type_name -> llmcenter.FileInfo
	0,  // 16: llmcenter.LlmCenter.ChatCompletions:input_type -> llmcenter.ChatCompletionsRequest
	2,  // 17: llmcenter.LlmCenter.ChatResume:input_type -> llmcenter.ChatResumeRequest
	22, // 18: llmcenter.LlmCenter.FileUpload:input_type -> llmcenter.FileUploadRequest
	4,  // 19: llmcenter.LlmCenter.GetConversations:input_type -> llmcenter.GetConversationsRequest
	6,  // 20: llmcenter.LlmCenter.GetConversationDetail:input_type -> llmcenter.GetConversationDetailRequest
	8,  // 21: llmcenter.LlmCenter.GetDocumentDetail:input_type -> llmcenter.GetDocumentDetailRequest
	11, // 22: llmcenter.LlmCenter.GetHistoryData:input_type -> llmcenter.GetHistoryDataRequest
	15, // 23: llmcenter.LlmCenter.EditDocument:input_type -> llmcenter.EditDocumentRequest
	17, // 24: llmcenter.LlmCenter.UpdateDocument:input_type -> llmcenter.UpdateDocumentRequest
	19, // 25: llmcenter.LlmCenter.ConvertMarkdown:input_type -> llmcenter.ConvertMarkdownRequest
	31, // 26: llmcenter.LlmCenter.ConvertMarkdownLink:input_type -> llmcenter.ConvertMarkdownLinkRequest
	1,  // 27: llmcenter.LlmCenter.ChatCompletions:output_type -> llmcenter.ChatCompletionsResponse
	3,  // 28: llmcenter.LlmCenter.ChatResume:output_type -> llmcenter.ChatResumeResponse
	24, // 29: llmcenter.LlmCenter.FileUpload:output_type -> llmcenter.FileUploadResponse
	5,  // 30: llmcenter.LlmCenter.GetConversations:output_type -> llmcenter.GetConversationsResponse
	7,  // 31: llmcenter.LlmCenter.GetConversationDetail:output_type -> llmcenter.GetConversationDetailResponse
	10, // 32: llmcenter.LlmCenter.GetDocumentDetail:output_type -> llmcenter.GetDocumentDetailResponse
	12, // 33: llmcenter.LlmCenter.GetHistoryData:output_type -> llmcenter.GetHistoryDataResponse
	16, // 34: llmcenter.LlmCenter.EditDocument:output_type -> llmcenter.EditDocumentResponse
	18, // 35: llmcenter.LlmCenter.UpdateDocument:output_type -> llmcenter.UpdateDocumentResponse
	20, // 36: llmcenter.LlmCenter.ConvertMarkdown:output_type -> llmcenter.ConvertMarkdownResponse
	32, // 37: llmcenter.LlmCenter.ConvertMarkdownLink:output_type -> llmcenter.ConvertMarkdownLinkResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_llmcenter_proto_init() }
func file_llmcenter_proto_init() {
	if File_llmcenter_proto != nil {
		return
	}
	file_llmcenter_proto_msgTypes[1].OneofWrappers = []any{
		(*ChatCompletionsResponse_Message)(nil),
		(*ChatCompletionsResponse_Interrupt)(nil),
		(*ChatCompletionsResponse_End)(nil),
	}
	file_llmcenter_proto_msgTypes[3].OneofWrappers = []any{
		(*ChatResumeResponse_Message)(nil),
		(*ChatResumeResponse_End)(nil),
	}
	file_llmcenter_proto_msgTypes[16].OneofWrappers = []any{
		(*EditDocumentResponse_Message)(nil),
		(*EditDocumentResponse_End)(nil),
	}
	file_llmcenter_proto_msgTypes[22].OneofWrappers = []any{
		(*FileUploadRequest_Info)(nil),
		(*FileUploadRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmcenter_proto_rawDesc), len(file_llmcenter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llmcenter_proto_goTypes,
		DependencyIndexes: file_llmcenter_proto_depIdxs,
		MessageInfos:      file_llmcenter_proto_msgTypes,
	}.Build()
	File_llmcenter_proto = out.File
	file_llmcenter_proto_goTypes = nil
	file_llmcenter_proto_depIdxs = nil
}
