Name: llmcenter.rpc
ListenOn: 0.0.0.0:8003
Mode: pro

Timeout:  180000 # 毫秒, 180000ms = 3 分钟

Log:
  ServiceName: llmcenter-rpc
  Level: error
  Mode: console
  SlowThreshold: 30000
  
Etcd:
  Hosts:
    - etcd:2379
  Key: llmcenter.rpc

DB:
  DataSource: 

XingChen:
  FlowID: ""
  ApiURL: ""
  ApiResumeURL: ""
  ApiSecret: ""
  ApiKey: ""
  UploadURL: ""
  FlagCode1: ""
  FlagCode2: ""

Redis:
  Host: redis:6379
  Type: node  # 单节点模式用 node，集群模式用 cluster
  Pass: ""    # 如果你的 Redis 有密码，在这里填写
  Tls: false
  Key: llmcenter:redis
  
Upload:
  BaseDir: /app/data/static

LlmApiClient:
  Timeout: 200  # s
  MaxIdleConns: 100
  MaxIdleConnsPerHost: 10
  IdleConnTimeout: 90  # s
  DisableCompression: true

Font:
  Path: "/app/deploy/fonts"

LuaFilters:
  Align: "/app/deploy/lua/align.lua"
  Gov:   "/app/deploy/lua/gov.lua"

Download:
  BaseURL: ""
  # 与 API 共享的签名密钥（两边保持一致）
  SignKey: ""
  # 链接有效期（秒）
  ExpireSeconds: 600